### ISSUE TITLE
Initial position shiftings with multiple shake actions

### ISSUE THREAD

**Issue by mertkasar** [tankorsmash/FrozaxShake-v3#1]
FShake action causes shiftings of the node's initial position when you want to apply multiple shakes at the same time to the node.

Let's say I want to create an explosion animation on the screen and want use FShake action as a callback to shake the screen layer when an explosion took place. Duration of the shake action is 1 second. And let's say I have an unfinished explosion on the screen when I want to create a new one while screen is already shaking.

The catch here is, it's certain that a shaking node's current position vector is different from it's initial one. And since FShake stores the target node's initial position before it starts to shake, second FShake action will store an displaced (shaking) position when starts. And it will eventually cause it place the target node to a different position when stop() method called.

Here is a further explanation;

Node's initial position: 0, 0
FShake1 comes in, stores initial position as: 0, 0
FShake1 moves the node to 3, 5 let's say
FShake2 comes in while FShake1 still in progress, stores initial position as 3, 5
FShake2 moves the node to -2, 4 
FShake1 finishes his job, calls stop() method, and moves the node to it's stored initial position 0, 0
FShake2 finishes his job, calls  stop() method, and moves the node to it's stored initial position 3, 5

As result, node will appear in 3, 5 while it should appear it's original initial position 0, 0

**Comment by tankorsmash** [comment]
Thanks for the fix!
